project:
  type: website

website:
  title: "Learning Shiny"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

filters:
  - shinylive
  - quarto
  - line-highlight

editor:
  render-on-save: true
